### ISSUE TITLE
Which OCaml version to use?

### ISSUE THREAD

**Issue by bobismijnnaam** [javert2/JaVerT2.0#1]
Dear Mr. Santos,

I am trying to run JaVerT2.0 on some example files. However I cannot get JaVerT to build. Which version of OCaml is required? I have tried 4.04, 4.07, and 4.06.1, but I've run into various errors (mostly packages not being available, having to install packages by hand, Z3 being renamed to z3, and errors that cmi files are for older versions). Trying each OCaml version separately costs a lot of time, which is why I am making an issue. I have been unable to find any notes in your repository indicating which version to use, but possibly I have overlooked them.

Another question: can you confirm that the following sequence of instructions should be enough to test JaVerT? Or are there any steps I am missing? I am sorry, I do not have any experience with OCaml.
```
$ make init
...
$ make default
...
$ ./scripts/JaVerT.sh my_file.js
```

I would greatly appreciate it if you could spare a moment of your time.

Kind regards,

Bob

**Comment by giltho** [comment]
Dear Mr. Rubbens,

Sorry to answer so late, here are the answers to your questions.
JaVerT2.0 has evolved into Gillian-JS (the instantiation of Gillian for Javascript, which has the exact same capabilities as JaVerT2.0 and works on the same model).
During this transition, we have made a lot of progress in facilitating the build process for Gillian and its instantiations. Here are the instructions:

---

**Basic Instructions**

First of all the new repository is located here : https://github.com/GillianPlatform/Gillian. Note that the build process is not working on Windows just now, but I am guessing you are either using Linux or macOS. 
In order to build Gillian, we ask you to install esy (https://esy.sh) which is a tool that simplifies the build and dependency management process. Unfortunately, it is only available through npm right now.

```
$ npm install -g esy
```

Once esy is installed, and the repository is cloned, you should be able to build the entire tool as well as its dependencies by simply using  the following command at the root of the project

```
$ esy
```

Once the project has been built, you can run any command in the "test environment" created by esy which simulates a globally installed toolchain by prefixing any command with esy x (more details [here](https://esy.sh/docs/en/commands.html#esy-x-command)).
You can for example run the following command to get the manual about verification (equivalent of JaVerT.sh) 

```
$ esy x gillian-js verify --help
```

In particular, running the following command should be enough to test JaVert:

```
$ esy x gillian-js verify my_file.js
```

**Global install (optional)**

In case you do not want to prefix every of you command with esy x (which has to be done by always being inside of the project), you may want to install Gillian-JS globally.
For this, once the project is built (after running esy ), you can run

```
$ esy release
$ npm install -g _release
```

Please do ignore the warnings saying "bad source file name".
After running these commands, you can run gillian-js as any other globally installed executable 

```
$ gillian-js verify --help
```

You can always safely uninstall it simply by running

```
$ npm uninstall -g gillian-ecosystem-dev
```

**Troubleshooting**

You might hit a permission error in the process of installing esy, in which case please run the following command OR [fix your npm installation](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md).
$ sudo npm install -g esy --unsafe-perm 

---

There is also more information about Gillian and Gillian-JS on the Gillian website https://gillianplatform.github.io/, but note that it is still very incomplete.
In any case, I would be glad to answer any more questions you may have. Don't hesitate to open an issue on the Gillian repository directly.

Best regards,
Sacha Ayoun

**Comment by bobismijnnaam** [comment]
Thanks, I'll ask my next questions in the Gillian repo.
